import "./globals.css";

import { Providers } from "./providers";
import { Figtree, Montserrat } from "next/font/google";
import clsx from "clsx";
import type { Metadata } from "next";
import Header from "@/components/layout/header/header";

const figtree = Figtree({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Nextik",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={clsx(figtree.className)}>
        <Providers>
          <Header />
          <main className='main-app'>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
